<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Waylonia.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Basin.Avalonia" />
    <PackageReference Include="Basin.Core" />
    <PackageReference Include="Basin.Desktop" />
    <PackageReference Include="Basin.Scene" />
    <PackageReference Include="Basin.Shell.Xdg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Waylonia/Waylonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
