<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <WayloniaPlatforms>portable</WayloniaPlatforms>
    <RootNamespace>Waylonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="waylonia" />
    <InternalsVisibleTo Include="Waylonia" />
    <InternalsVisibleTo Include="Waylonia.UI.Desktop" />
    <InternalsVisibleTo Include="Waylonia.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/Waylonia_Logo.png" LogicalName="Waylonia.Waylonia_Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Waylonia.Core/Waylonia.Core.csproj" />
    <PackageReference Include="Basin.Avalonia.View" />
    <PackageReference Include="Basin.UI.Avalonia" />
    <PackageReference Include="BluerCurve" />
    <PackageReference Include="BluerCurve.Icons" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Svg.Skia" />
  </ItemGroup>

</Project>
