<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <WayloniaPlatforms>portable</WayloniaPlatforms>
    <RootNamespace>Waylonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="waylonia" />
    <InternalsVisibleTo Include="Waylonia" />
    <InternalsVisibleTo Include="Waylonia.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Waylonia.Core/Waylonia.Core.csproj" />
    <ProjectReference Include="../../external/Tmds.Ssh/src/Tmds.Ssh/Tmds.Ssh.csproj" />
  </ItemGroup>

</Project>
