<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Waylonia.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="../../external/basin/src/Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Desktop/Basin.Desktop.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Freedesktop/Basin.Freedesktop.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Hosted/Basin.Hosted.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Scene/Basin.Scene.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Shell.Xdg/Basin.Shell.Xdg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Waylonia.Core/Waylonia.Core.csproj" />
    <ProjectReference Include="../../src/Waylonia.Ssh.Tmds/Waylonia.Ssh.Tmds.csproj" />
  </ItemGroup>

</Project>
