<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Waylonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="waylonia" />
    <InternalsVisibleTo Include="Waylonia.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Waylonia.UI/Waylonia.UI.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Avalonia/Basin.Avalonia.csproj" />
    <PackageReference Include="BluerCurve" />
  </ItemGroup>

</Project>
