<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Waylonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Waylonia.Ssh.Tmds" />
    <InternalsVisibleTo Include="Waylonia.UI" />
    <InternalsVisibleTo Include="waylonia" />
    <InternalsVisibleTo Include="Waylonia.Core.Tests" />
    <InternalsVisibleTo Include="Waylonia.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shell/Themes/Atlanta/metacity-theme-1.xml" LogicalName="Waylonia.Themes.Atlanta.metacity-theme-1.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Basin.Hosted" />
    <PackageReference Include="Basin.Frames.Metacity" />
    <PackageReference Include="Basin.Freedesktop" />
    <PackageReference Include="Basin.Render.Skia" />
    <PackageReference Include="Basin.Shell.Nested" />
    <PackageReference Include="Basin.Transport.Waypipe" />
    <PackageReference Include="Basin.UI.Skia" />
    <PackageReference Include="Basin.Video.FFmpeg" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

</Project>
