<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <WayloniaPlatforms>portable</WayloniaPlatforms>
    <RootNamespace>Waylonia</RootNamespace>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Waylonia.Ssh.Tmds" />
    <InternalsVisibleTo Include="Waylonia.Audio.MiniAudio" />
    <InternalsVisibleTo Include="Waylonia.UI" />
    <InternalsVisibleTo Include="Waylonia.UI.Desktop" />
    <InternalsVisibleTo Include="waylonia" />
    <InternalsVisibleTo Include="Waylonia" />
    <InternalsVisibleTo Include="Waylonia.Core.Tests" />
    <InternalsVisibleTo Include="Waylonia.UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shell/Themes/Atlanta/metacity-theme-1.xml" LogicalName="Waylonia.Themes.Atlanta.metacity-theme-1.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../external/basin/src/Basin.Hosted/Basin.Hosted.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Frames.Metacity/Basin.Frames.Metacity.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Freedesktop/Basin.Freedesktop.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Render.Skia/Basin.Render.Skia.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Shell.Nested/Basin.Shell.Nested.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.Transport.Waypipe/Basin.Transport.Waypipe.csproj" />
    <ProjectReference Include="../../external/basin/src/Basin.UI.Skia/Basin.UI.Skia.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

</Project>
